# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/grdm-tools',
                'doc_host': 'https://nakamura196.github.io',
                'git_url': 'https://github.com/nakamura196/grdm-tools',
                'lib_path': 'grdm_tools'},
  'syms': { 'grdm_tools.core': { 'grdm_tools.core.GrdmClient': ('core.html#grdmclient', 'grdm_tools/core.py'),
                                 'grdm_tools.core.GrdmClient.__init__': ('core.html#grdmclient.__init__', 'grdm_tools/core.py'),
                                 'grdm_tools.core.GrdmClient.get_zotero_contents': ( 'core.html#grdmclient.get_zotero_contents',
                                                                                     'grdm_tools/core.py'),
                                 'grdm_tools.core.GrdmClient.get_zotero_folder_id': ( 'core.html#grdmclient.get_zotero_folder_id',
                                                                                      'grdm_tools/core.py'),
                                 'grdm_tools.core.GrdmClient.update_file': ('core.html#grdmclient.update_file', 'grdm_tools/core.py'),
                                 'grdm_tools.core.GrdmClient.upload_file': ('core.html#grdmclient.upload_file', 'grdm_tools/core.py')}}}
